# Generated by Django 5.2.8 on 2025-11-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(help_text='Enter order ID')),
                ('customer_name', models.CharField(help_text='Enter customer name', max_length=100)),
                ('total_amount', models.IntegerField(help_text='Enter Total Amount')),
                ('order_date', models.DateTimeField(help_text='Enter order date')),
                ('status', models.CharField(help_text='Enter Order Status')),
            ],
        ),
    ]
